const genai = require('@google/genai');
const { sanitizeText } = require('../../../utils/textSanitizer');
const { getStaticFileUrl } = require('../../../utils/urlUtils');
const veoGeneration = require('./veoGeneration');
const fs = require('fs');
const path = require('path');
const { v4: uuidv4 } = require('uuid');
const { exec } = require('child_process');
const { promisify } = require('util');

const execAsync = promisify(exec);
const veoClient = new genai.GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY
});

/**
 * WhatsApp-specific video generation operations
 */
class WhatsAppVideoGeneration {
  /**
   * Poll operation until completion (for WhatsApp)
   */
  async pollOperation(operation, operationType = 'video generation') {
    console.log('⏳ Polling for video generation completion...');
    const { TIME } = require('../../../utils/constants');
    const maxWaitTime = TIME.VIDEO_GENERATION_TIMEOUT;
    const startTime = Date.now();
    let pollAttempts = 0;

    while (!operation.done) {
      if (Date.now() - startTime > maxWaitTime) {
        console.error(`❌ Veo 3 ${operationType} timed out`);
        return {
          success: false,
          error: 'Video generation timed out after 10 minutes'
        };
      }
      await new Promise(resolve => setTimeout(resolve, 10000));
      pollAttempts++;
      console.log(`🔄 Polling attempt ${pollAttempts} for Veo 3 ${operationType}`);
      operation = await veoClient.operations.getVideosOperation({ operation });
    }

    return { success: true, operation };
  }

  /**
   * Validate operation response (for WhatsApp)
   */
  validateOperationResponse(operation) {
    if (!operation.response) {
      console.error('❌ No response in operation:', operation);
      return {
        success: false,
        error: 'No response received from Veo 3 API'
      };
    }

    if (!operation.response.generatedVideos) {
      console.error('❌ No generatedVideos in response:', operation.response);

      let errorMessage = 'No generated videos in Veo 3 response';
      if (operation.response.raiMediaFilteredReasons && operation.response.raiMediaFilteredReasons.length > 0) {
        errorMessage = operation.response.raiMediaFilteredReasons[0];
      }

      return {
        success: false,
        error: errorMessage
      };
    }

    if (!operation.response.generatedVideos.length || !operation.response.generatedVideos[0]) {
      console.error('❌ Empty generatedVideos array:', operation.response.generatedVideos);

      let errorMessage = 'No videos were generated by Veo 3';
      if (operation.response.raiMediaFilteredReasons && operation.response.raiMediaFilteredReasons.length > 0) {
        errorMessage = operation.response.raiMediaFilteredReasons[0];
      }

      return {
        success: false,
        error: errorMessage
      };
    }

    if (!operation.response.generatedVideos[0].video) {
      console.error('❌ No video file in first generated video:', operation.response.generatedVideos[0]);
      return {
        success: false,
        error: 'Generated video has no file reference'
      };
    }

    return { success: true };
  }

  /**
   * Download video file from Veo (for WhatsApp)
   */
  async downloadVideoFile(videoFile, fileNamePrefix = 'veo3') {
      const fileName = `${fileNamePrefix}_video_${uuidv4()}.mp4`;
      const filePath = path.join(__dirname, '../../..', 'public', 'tmp', fileName);
    const tmpDir = path.dirname(filePath);

    if (!fs.existsSync(tmpDir)) {
      fs.mkdirSync(tmpDir, { recursive: true });
    }

    try {
      await veoClient.files.download({ file: videoFile, downloadPath: filePath });
      console.log('📥 SDK download completed');
      return { success: true, filePath, fileName };
    } catch (downloadError) {
      console.error('❌ SDK download failed:', downloadError);
      return {
        success: false,
        error: `Failed to download video file: ${downloadError.message}`
      };
    }
  }

  /**
   * Wait for file to be ready (for WhatsApp, larger minimum size)
   */
  async waitForFileReady(filePath) {
    let retries = 0;
    let fileReady = false;

    while (!fileReady && retries < 15) {
      await new Promise(resolve => setTimeout(resolve, 200));

      if (fs.existsSync(filePath)) {
        try {
          const stats = fs.statSync(filePath);

          if (stats.size > 0) {
            await new Promise(resolve => setTimeout(resolve, 500));
            const newStats = fs.statSync(filePath);

            if (newStats.size === stats.size && stats.size > 100000) { // At least 100KB for video
              fileReady = true;
              break;
            }
          }
        } catch (statError) {
          // Continue retrying
        }
      }
      retries++;
    }

    if (!fileReady) {
      console.error('❌ Video file was not properly downloaded');
      return {
        success: false,
        error: 'Video file was not downloaded successfully'
      };
    }

    return { success: true };
  }

  /**
   * Convert video to WhatsApp-compatible format
   */
  async convertVideoForWhatsApp(filePath, fileName, req) {
    console.log('🎬 Converting video to WhatsApp-compatible format...');
      const convertedFileName = fileName.replace('.mp4', '_converted.mp4');
      const convertedFilePath = path.join(__dirname, '../../..', 'public', 'tmp', convertedFileName);

    try {
      await execAsync(`ffmpeg -i "${filePath}" -c:v libx264 -preset medium -crf 23 -c:a aac -b:a 128k -movflags +faststart "${convertedFilePath}" -y`);
      console.log('✅ Video converted successfully');
      
      // Delete original file
      try {
        fs.unlinkSync(filePath);
      } catch (unlinkError) {
        console.warn('⚠️ Could not delete original file:', unlinkError.message);
      }

      return {
        success: true,
        filePath: convertedFilePath,
        fileName: convertedFileName
      };
    } catch (convertError) {
      console.error('❌ Video conversion failed:', convertError);
      console.log('⚠️ Using original file without conversion');
      return {
        success: false,
        fallback: true,
        filePath: filePath,
        fileName: fileName
      };
    }
  }

  /**
   * Generate video for WhatsApp from text prompt
   */
  async generateVideoForWhatsApp(prompt, req = null) {
    try {
      console.log('🎬 Starting Veo 3 text-to-video generation - Preview version');
      const cleanPrompt = sanitizeText(prompt);

      let operation = await veoClient.models.generateVideos({
        model: "veo-3.1-generate-preview",
        prompt: cleanPrompt,
        config: {
          aspectRatio: "9:16"
        }
      });

      const pollResult = await this.pollOperation(operation, 'text-to-video generation');
      if (!pollResult.success) {
        return pollResult;
      }
      operation = pollResult.operation;

      const validationResult = this.validateOperationResponse(operation);
      if (!validationResult.success) {
        return validationResult;
      }

      const videoFile = operation.response.generatedVideos[0].video;
      const downloadResult = await this.downloadVideoFile(videoFile, 'veo3');
      if (!downloadResult.success) {
        return downloadResult;
      }

      const { filePath, fileName } = downloadResult;
      const fileReadyResult = await this.waitForFileReady(filePath);
      if (!fileReadyResult.success) {
        return fileReadyResult;
      }

      const videoUrl = getStaticFileUrl(fileName, req);

      console.log('✅ Veo 3 text-to-video generated successfully');
      console.log(`🎬 Video saved to: ${filePath}`);
      console.log(`🔗 Public URL: ${videoUrl}`);

      return {
        success: true,
        videoUrl: videoUrl,
        description: cleanPrompt,
        fileName: fileName
      };
    } catch (err) {
      console.error('❌ Veo 3 text-to-video generation error:', err);
      return {
        success: false,
        error: err.message || 'Unknown error occurred during video generation'
      };
    }
  }

  /**
   * Generate video for WhatsApp from image and text prompt
   */
  async generateVideoFromImageForWhatsApp(prompt, imageBuffer, req = null) {
    try {
      console.log('🎬 Starting Veo 3 image-to-video generation - Stable version');
      const cleanPrompt = sanitizeText(prompt);
      const imageBase64 = imageBuffer.toString('base64');

      let operation = await veoClient.models.generateVideos({
        model: "veo-3.1-generate-preview",
        prompt: cleanPrompt,
        image: {
          imageBytes: imageBase64,
          mimeType: "image/jpeg",
        },
        config: {
          aspectRatio: "9:16"
        }
      });

      const pollResult = await this.pollOperation(operation, 'image-to-video generation');
      if (!pollResult.success) {
        return pollResult;
      }
      operation = pollResult.operation;

      const validationResult = this.validateOperationResponse(operation);
      if (!validationResult.success) {
        return validationResult;
      }

      const videoFile = operation.response.generatedVideos[0].video;
      const downloadResult = await this.downloadVideoFile(videoFile, 'veo3_image');
      if (!downloadResult.success) {
        return downloadResult;
      }

      const { filePath, fileName } = downloadResult;
      const fileReadyResult = await this.waitForFileReady(filePath);
      if (!fileReadyResult.success) {
        return fileReadyResult;
      }

      // Convert video to WhatsApp-compatible format
      const convertResult = await this.convertVideoForWhatsApp(filePath, fileName, req);
      
      let finalFileName, finalFilePath;
      if (convertResult.success) {
        finalFileName = convertResult.fileName;
        finalFilePath = convertResult.filePath;
      } else {
        finalFileName = convertResult.fileName;
        finalFilePath = convertResult.filePath;
      }

      const videoUrl = getStaticFileUrl(finalFileName, req);

      console.log('✅ Veo 3 image-to-video generated and converted successfully');
      console.log(`🎬 Video saved to: ${finalFilePath}`);
      console.log(`🔗 Public URL: ${videoUrl}`);

      return {
        success: true,
        videoUrl: videoUrl,
        description: cleanPrompt,
        fileName: finalFileName
      };
    } catch (err) {
      console.error('❌ Veo 3 image-to-video generation error:', err);
      return {
        success: false,
        error: err.message || 'Unknown error occurred during image-to-video generation'
      };
    }
  }
}

module.exports = new WhatsAppVideoGeneration();

