// eslint-disable-next-line @typescript-eslint/no-require-imports
const genai = require('@google/genai');
import { sanitizeText } from '../../../utils/textSanitizer';
import { getStaticFileUrl } from '../../../utils/urlUtils';
import { createTempFilePath } from '../../../utils/tempFileUtils';
import fs from 'fs';
import path from 'path';
import { v4 as uuidv4 } from 'uuid';
import { exec } from 'child_process';
import { promisify } from 'util';
import { TIME } from '../../../utils/constants';
import { Request } from 'express';
import logger from '../../../utils/logger';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const ffmpegPath = require('ffmpeg-static');

const execAsync = promisify(exec);
const ffmpeg = (ffmpegPath as unknown as string);
const veoClient = new genai.GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY
});

/**
 * Poll result
 */
interface PollResult {
  success?: boolean;
  operation?: unknown;
  error?: string;
}

/**
 * Validation result
 */
interface ValidationResult {
  success: boolean;
  error?: string;
}

/**
 * Download result
 */
interface DownloadResult {
  success: boolean;
  filePath?: string;
  fileName?: string;
  error?: string;
}

/**
 * File ready result
 */
interface FileReadyResult {
  success: boolean;
  error?: string;
}

/**
 * Convert result
 */
interface ConvertResult {
  success: boolean;
  fallback?: boolean;
  filePath: string;
  fileName: string;
}

/**
 * WhatsApp video result
 */
interface WhatsAppVideoResult {
  success: boolean;
  videoUrl?: string;
  description?: string;
  fileName?: string;
  error?: string;
}

/**
 * WhatsApp-specific video generation operations
 */
class WhatsAppVideoGeneration {
  /**
   * Poll operation until completion (for WhatsApp)
   */
  async pollOperation(operation: unknown, operationType = 'video generation'): Promise<PollResult> {
    logger.info('⏳ Polling for video generation completion...');
    const maxWaitTime = TIME.VIDEO_GENERATION_TIMEOUT;
    const startTime = Date.now();
    let pollAttempts = 0;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let currentOperation = operation as any;
    while (!currentOperation.done) {
      if (Date.now() - startTime > maxWaitTime) {
        logger.error(`❌ Veo 3 ${operationType} timed out`);
        return {
          success: false,
          error: 'Video generation timed out after 10 minutes'
        };
      }
      await new Promise(resolve => setTimeout(resolve, 10000));
      pollAttempts++;
      logger.info(`🔄 Polling attempt ${pollAttempts} for Veo 3 ${operationType}`);
      currentOperation = await veoClient.operations.getVideosOperation({ operation: currentOperation });
    }

    return { success: true, operation: currentOperation };
  }

  /**
   * Validate operation response (for WhatsApp)
   */
  validateOperationResponse(operation: unknown): ValidationResult {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const op = operation as any;
    if (!op.response) {
      logger.error('❌ No response in operation:', operation as Error);
      return {
        success: false,
        error: 'No response received from Veo 3 API'
      };
    }

    if (!op.response.generatedVideos) {
      logger.error('❌ No generatedVideos in response:', op.response as Error);

      let errorMessage = 'No generated videos in Veo 3 response';
      if (op.response.raiMediaFilteredReasons && op.response.raiMediaFilteredReasons.length > 0) {
        errorMessage = op.response.raiMediaFilteredReasons[0];
      }

      return {
        success: false,
        error: errorMessage
      };
    }

    if (!op.response.generatedVideos.length || !op.response.generatedVideos[0]) {
      logger.error('❌ Empty generatedVideos array:', op.response.generatedVideos as Error);

      let errorMessage = 'No videos were generated by Veo 3';
      if (op.response.raiMediaFilteredReasons && op.response.raiMediaFilteredReasons.length > 0) {
        errorMessage = op.response.raiMediaFilteredReasons[0];
      }

      return {
        success: false,
        error: errorMessage
      };
    }

    if (!op.response.generatedVideos[0].video) {
      logger.error('❌ No video file in first generated video:', op.response.generatedVideos[0] as Error);
      return {
        success: false,
        error: 'Generated video has no file reference'
      };
    }

    return { success: true };
  }

  /**
   * Download video file from Veo (for WhatsApp)
   */
  async downloadVideoFile(videoFile: unknown, fileNamePrefix = 'veo3'): Promise<DownloadResult> {
    const fileName = `${fileNamePrefix}_video_${uuidv4()}.mp4`;
    // Use createTempFilePath for consistent path resolution (uses config.paths.tmp)
    const filePath = createTempFilePath(fileName);
    const tmpDir = path.dirname(filePath);

    if (!fs.existsSync(tmpDir)) {
      fs.mkdirSync(tmpDir, { recursive: true });
    }

    try {
      await veoClient.files.download({ file: videoFile, downloadPath: filePath });
      logger.info('📥 SDK download completed');
      return { success: true, filePath, fileName };
    } catch (downloadError: unknown) {
      const errorMessage = downloadError instanceof Error ? downloadError.message : String(downloadError);
      logger.error('❌ SDK download failed:', downloadError as Error);
      return {
        success: false,
        error: `Failed to download video file: ${errorMessage}`
      };
    }
  }

  /**
   * Wait for file to be ready (for WhatsApp, larger minimum size)
   */
  async waitForFileReady(filePath: string): Promise<FileReadyResult> {
    let retries = 0;
    let fileReady = false;

    while (!fileReady && retries < 15) {
      await new Promise(resolve => setTimeout(resolve, 200));

      if (fs.existsSync(filePath)) {
        try {
          const stats = fs.statSync(filePath);

          if (stats.size > 0) {
            await new Promise(resolve => setTimeout(resolve, 500));
            const newStats = fs.statSync(filePath);

            if (newStats.size === stats.size && stats.size > 100000) { // At least 100KB for video
              fileReady = true;
              break;
            }
          }
        } catch (_statError) {
          // Continue retrying
        }
      }
      retries++;
    }

    if (!fileReady) {
      logger.error('❌ Video file was not properly downloaded');
      return {
        success: false,
        error: 'Video file was not downloaded successfully'
      };
    }

    return { success: true };
  }

  /**
   * Convert video to WhatsApp-compatible format
   */
  async convertVideoForWhatsApp(filePath: string, fileName: string, _req: Request | null): Promise<ConvertResult> {
    logger.info('🎬 Converting video to WhatsApp-compatible format...');
    const convertedFileName = fileName.replace('.mp4', '_converted.mp4');
    // Use createTempFilePath for consistent path resolution (uses config.paths.tmp)
    const convertedFilePath = createTempFilePath(convertedFileName);

    try {
      await execAsync(`${ffmpeg} -i "${filePath}" -c:v libx264 -preset medium -crf 23 -c:a aac -b:a 128k -movflags +faststart "${convertedFilePath}" -y`);
      logger.info('✅ Video converted successfully');
      
      // Delete original file
      try {
        fs.unlinkSync(filePath);
      } catch (unlinkError: unknown) {
        const errorMessage = unlinkError instanceof Error ? unlinkError.message : String(unlinkError);
        logger.warn('⚠️ Could not delete original file:', errorMessage);
      }

      return {
        success: true,
        filePath: convertedFilePath,
        fileName: convertedFileName
      };
    } catch (convertError: unknown) {
      logger.error('❌ Video conversion failed:', convertError as Error);
      logger.warn('⚠️ Using original file without conversion');
      return {
        success: false,
        fallback: true,
        filePath: filePath,
        fileName: fileName
      };
    }
  }

  /**
   * Generate video for WhatsApp from text prompt
   */
  async generateVideoForWhatsApp(prompt: string, req: Request | null = null): Promise<WhatsAppVideoResult> {
    try {
      logger.info('🎬 Starting Veo 3 text-to-video generation - Preview version');
      const cleanPrompt = sanitizeText(prompt);

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      let operation = await veoClient.models.generateVideos({
        model: "veo-3.1-generate-preview",
        prompt: cleanPrompt,
        config: {
          aspectRatio: "9:16"
        }
      } as any);

      const pollResult = await this.pollOperation(operation, 'text-to-video generation');
      if (!pollResult.success) {
        return {
          success: false,
          error: pollResult.error
        };
      }
      operation = pollResult.operation;

      const validationResult = this.validateOperationResponse(operation);
      if (!validationResult.success) {
        return {
          success: false,
          error: validationResult.error
        };
      }

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const op = operation as any;
      const videoFile = op.response.generatedVideos[0].video;
      const downloadResult = await this.downloadVideoFile(videoFile, 'veo3');
      if (!downloadResult.success || !downloadResult.filePath || !downloadResult.fileName) {
        return {
          success: false,
          error: downloadResult.error
        };
      }

      const { filePath, fileName } = downloadResult;
      const fileReadyResult = await this.waitForFileReady(filePath);
      if (!fileReadyResult.success) {
        return {
          success: false,
          error: fileReadyResult.error
        };
      }

      const videoUrl = getStaticFileUrl(fileName, req);

      logger.info('✅ Veo 3 text-to-video generated successfully');
      logger.info(`🎬 Video saved to: ${filePath}`);
      logger.info(`🔗 Public URL: ${videoUrl}`);

      return {
        success: true,
        videoUrl: videoUrl,
        description: cleanPrompt,
        fileName: fileName
      };
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred during video generation';
      logger.error('❌ Veo 3 text-to-video generation error:', err as Error);
      return {
        success: false,
        error: errorMessage
      };
    }
  }

  /**
   * Generate video for WhatsApp from image and text prompt
   */
  async generateVideoFromImageForWhatsApp(prompt: string, imageBuffer: Buffer, req: Request | null = null): Promise<WhatsAppVideoResult> {
    try {
      logger.info('🎬 Starting Veo 3 image-to-video generation - Stable version');
      const cleanPrompt = sanitizeText(prompt);
      const imageBase64 = imageBuffer.toString('base64');

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      let operation = await veoClient.models.generateVideos({
        model: "veo-3.1-generate-preview",
        prompt: cleanPrompt,
        image: {
          imageBytes: imageBase64,
          mimeType: "image/jpeg",
        },
        config: {
          aspectRatio: "9:16"
        }
      } as any);

      const pollResult = await this.pollOperation(operation, 'image-to-video generation');
      if (!pollResult.success) {
        return {
          success: false,
          error: pollResult.error
        };
      }
      operation = pollResult.operation;

      const validationResult = this.validateOperationResponse(operation);
      if (!validationResult.success) {
        return {
          success: false,
          error: validationResult.error
        };
      }

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const op = operation as any;
      const videoFile = op.response.generatedVideos[0].video;
      const downloadResult = await this.downloadVideoFile(videoFile, 'veo3_image');
      if (!downloadResult.success || !downloadResult.filePath || !downloadResult.fileName) {
        return {
          success: false,
          error: downloadResult.error
        };
      }

      const { filePath, fileName } = downloadResult;
      const fileReadyResult = await this.waitForFileReady(filePath);
      if (!fileReadyResult.success) {
        return {
          success: false,
          error: fileReadyResult.error
        };
      }

      // Convert video to WhatsApp-compatible format
      const convertResult = await this.convertVideoForWhatsApp(filePath, fileName, req);
      
      let finalFileName: string;
      let finalFilePath: string;
      if (convertResult.success) {
        finalFileName = convertResult.fileName;
        finalFilePath = convertResult.filePath;
      } else {
        finalFileName = convertResult.fileName;
        finalFilePath = convertResult.filePath;
      }

      const videoUrl = getStaticFileUrl(finalFileName, req);

      logger.info('✅ Veo 3 image-to-video generated and converted successfully');
      logger.info(`🎬 Video saved to: ${finalFilePath}`);
      logger.info(`🔗 Public URL: ${videoUrl}`);

      return {
        success: true,
        videoUrl: videoUrl,
        description: cleanPrompt,
        fileName: finalFileName
      };
    } catch (err: unknown) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred during image-to-video generation';
      logger.error('❌ Veo 3 image-to-video generation error:', err as Error);
      return {
        success: false,
        error: errorMessage
      };
    }
  }
}

export default new WhatsAppVideoGeneration();

