/**
 * Location service constants and data
 */

const { loadJson } = require('./helpers');

const countryBoundsData = loadJson('../../utils/countryBounds.json');
const cityBoundsData = loadJson('../../utils/cityBounds.json');

const cityKeywords = {
  'תל אביב': true, 'tel aviv': true, 'תל-אביב': true,
  'ירושלים': true, 'jerusalem': true,
  'חיפה': true, 'haifa': true,
  'באר שבע': true, 'beer sheva': true, 'באר-שבע': true,
  'אילת': true, 'eilat': true,
  'נתניה': true, 'netanya': true,
  'פתח תקווה': true, 'petah tikva': true, 'פתח-תקווה': true,
  'ראשון לציון': true, 'rishon lezion': true, 'ראשון-לציון': true,
  'ניו יורק': true, 'new york': true, 'ny': true, 'nyc': true,
  "לוס אנג'לס": true, 'los angeles': true, 'la': true,
  'לונדון': true, 'london': true,
  'פריז': true, 'paris': true,
  'ברלין': true, 'berlin': true,
  'מדריד': true, 'madrid': true,
  'רומא': true, 'rome': true,
  'מילאנו': true, 'milan': true,
  'ברצלונה': true, 'barcelona': true,
  'אמסטרדם': true, 'amsterdam': true,
  'טוקיו': true, 'tokyo': true,
  'סיאול': true, 'seoul': true,
  "בייג'ינג": true, 'beijing': true, 'פקין': true,
  'שנגחאי': true, 'shanghai': true,
  'דובאי': true, 'dubai': true,
  'סינגפור': true, 'singapore': true,
  'הונג קונג': true, 'hong kong': true,
  'בנגקוק': true, 'bangkok': true,
  'איסטנבול': true, 'istanbul': true,
  'קהיר': true, 'cairo': true,
  'מומבאי': true, 'mumbai': true,
  'דלהי': true, 'delhi': true,
  'סידני': true, 'sydney': true,
  'מלבורן': true, 'melbourne': true,
  'טורונטו': true, 'toronto': true,
  'ונקובר': true, 'vancouver': true,
  'מכסיקו סיטי': true, 'mexico city': true,
  "ריו דה ז'נרו": true, 'rio de janeiro': true, 'rio': true,
  'סאו פאולו': true, 'sao paulo': true,
  'בואנוס איירס': true, 'buenos aires': true,
  'קייפטאון': true, 'cape town': true,
  'יוהנסבורג': true, 'johannesburg': true,
  'מוסקבה': true, 'moscow': true,
  'סנט פטרבורג': true, 'saint petersburg': true, 'st petersburg': true,
  'ורשה': true, 'warsaw': true,
  'פראג': true, 'prague': true,
  'בודפשט': true, 'budapest': true,
  'וינה': true, 'vienna': true,
  'ציריך': true, 'zurich': true,
  "ג'נבה": true, 'geneva': true,
  'בריסל': true, 'brussels': true,
  'אתונה': true, 'athens': true,
  'ליסבון': true, 'lisbon': true,
  'קופנהגן': true, 'copenhagen': true,
  'שטוקהולם': true, 'stockholm': true,
  'אוסלו': true, 'oslo': true,
  'הלסינקי': true, 'helsinki': true,
  'דבלין': true, 'dublin': true
};

const regionMap = {
  'סלובניה': { continent: 'Southern Europe', display: 'סלובניה' },
  'slovenia': { continent: 'Southern Europe', display: 'Slovenia' },
  'סלובקיה': 'Eastern Europe',
  'slovakia': 'Eastern Europe',
  'פולין': 'Eastern Europe',
  'poland': 'Eastern Europe',
  'גרמניה': 'Western Europe',
  'germany': 'Western Europe',
  'צרפת': 'Western Europe',
  'france': 'Western Europe',
  'ספרד': 'Southern Europe',
  'spain': 'Southern Europe',
  'איטליה': 'Southern Europe',
  'italy': 'Southern Europe',
  'בריטניה': 'UK & Ireland',
  'britain': 'UK & Ireland',
  'uk': 'UK & Ireland',
  'אנגליה': 'UK & Ireland',
  'england': 'UK & Ireland',
  'שוודיה': 'Scandinavia',
  'sweden': 'Scandinavia',
  'נורווגיה': 'Scandinavia',
  'norway': 'Scandinavia',
  'דנמרק': 'Scandinavia',
  'denmark': 'Scandinavia',
  'פינלנד': 'Scandinavia',
  'finland': 'Scandinavia',
  'רוסיה': 'Eastern Europe',
  'russia': 'Eastern Europe',
  'טורקיה': 'Levant & Turkey',
  'turkey': 'Levant & Turkey',
  'יוון': 'Southern Europe',
  'greece': 'Southern Europe',
  'פורטוגל': 'Southern Europe',
  'portugal': 'Southern Europe',
  'הולנד': 'Western Europe',
  'netherlands': 'Western Europe',
  'בלגיה': 'Western Europe',
  'belgium': 'Western Europe',
  'שוויץ': 'Western Europe',
  'switzerland': 'Western Europe',
  'אוסטריה': 'Western Europe',
  'austria': 'Western Europe',
  'צ\'כיה': 'Eastern Europe',
  'czech': 'Eastern Europe',
  'צ\'ילה': 'Chile & Argentina',
  'chile': 'Chile & Argentina',
  'פרו': 'Andean Countries',
  'peru': 'Andean Countries',
  'קולומביה': 'Andean Countries',
  'colombia': 'Andean Countries',
  'מצרים': 'North Africa',
  'egypt': 'North Africa',
  'מרוקו': 'North Africa',
  'morocco': 'North Africa',
  'דרום אפריקה': 'Southern Africa',
  'south africa': 'Southern Africa',
  'ניגריה': 'West Africa',
  'nigeria': 'West Africa',
  'קניה': 'East Africa',
  'kenya': 'East Africa',
  'אוסטרליה': 'Australia',
  'australia': 'Australia',
  'ניו זילנד': 'New Zealand',
  'new zealand': 'New Zealand',
  'אירופה': { continent: 'MULTI_EUROPE', display: 'אירופה', multiRegions: ['Western Europe', 'Eastern Europe', 'Southern Europe', 'Scandinavia', 'UK & Ireland'] },
  'europe': { continent: 'MULTI_EUROPE', display: 'Europe', multiRegions: ['Western Europe', 'Eastern Europe', 'Southern Europe', 'Scandinavia', 'UK & Ireland'] },
  'אסיה': { continent: 'MULTI_ASIA', display: 'אסיה', multiRegions: ['China Mainland', 'Japan', 'Korea', 'Mainland Southeast Asia', 'India', 'Pakistan & Afghanistan'] },
  'asia': { continent: 'MULTI_ASIA', display: 'Asia', multiRegions: ['China Mainland', 'Japan', 'Korea', 'Mainland Southeast Asia', 'India', 'Pakistan & Afghanistan'] },
  'מזרח אסיה': { continent: 'MULTI_EAST_ASIA', display: 'מזרח אסיה', multiRegions: ['China Mainland', 'Japan', 'Korea'] },
  'east asia': { continent: 'MULTI_EAST_ASIA', display: 'East Asia', multiRegions: ['China Mainland', 'Japan', 'Korea'] },
  'דרום אסיה': { continent: 'India', display: 'דרום אסיה' },
  'south asia': { continent: 'India', display: 'South Asia' },
  'דרום מזרח אסיה': { continent: 'MULTI_SOUTHEAST_ASIA', display: 'דרום מזרח אסיה', multiRegions: ['Mainland Southeast Asia', 'Indonesia West', 'Philippines'] },
  'southeast asia': { continent: 'MULTI_SOUTHEAST_ASIA', display: 'Southeast Asia', multiRegions: ['Mainland Southeast Asia', 'Indonesia West', 'Philippines'] },
  'מזרח התיכון': { continent: 'MULTI_MIDDLE_EAST', display: 'מזרח התיכון', multiRegions: ['Levant & Turkey', 'Arabian Peninsula', 'Iran'] },
  'middle east': { continent: 'MULTI_MIDDLE_EAST', display: 'Middle East', multiRegions: ['Levant & Turkey', 'Arabian Peninsula', 'Iran'] },
  'אמריקה': { continent: 'MULTI_AMERICAS', display: 'אמריקה', multiRegions: ['Eastern USA', 'Western USA', 'Eastern Canada', 'Western Canada', 'Mexico', 'Brazil North', 'Brazil South', 'Chile & Argentina'] },
  'america': { continent: 'MULTI_AMERICAS', display: 'America', multiRegions: ['Eastern USA', 'Western USA', 'Eastern Canada', 'Western Canada', 'Mexico', 'Brazil North', 'Brazil South', 'Chile & Argentina'] },
  'צפון אמריקה': { continent: 'MULTI_NORTH_AMERICA', display: 'צפון אמריקה', multiRegions: ['Eastern USA', 'Western USA', 'Eastern Canada', 'Western Canada', 'Mexico'] },
  'north america': { continent: 'MULTI_NORTH_AMERICA', display: 'North America', multiRegions: ['Eastern USA', 'Western USA', 'Eastern Canada', 'Western Canada', 'Mexico'] },
  'דרום אמריקה': { continent: 'MULTI_SOUTH_AMERICA', display: 'דרום אמריקה', multiRegions: ['Brazil North', 'Brazil South', 'Andean Countries', 'Chile & Argentina'] },
  'south america': { continent: 'MULTI_SOUTH_AMERICA', display: 'South America', multiRegions: ['Brazil North', 'Brazil South', 'Andean Countries', 'Chile & Argentina'] },
  'אפריקה': { continent: 'MULTI_AFRICA', display: 'אפריקה', multiRegions: ['North Africa', 'West Africa', 'East Africa', 'Southern Africa'] },
  'africa': { continent: 'MULTI_AFRICA', display: 'Africa', multiRegions: ['North Africa', 'West Africa', 'East Africa', 'Southern Africa'] },
  'אוקיאניה': { continent: 'MULTI_OCEANIA', display: 'אוקיאניה', multiRegions: ['Australia', 'New Zealand'] },
  'oceania': { continent: 'MULTI_OCEANIA', display: 'Oceania', multiRegions: ['Australia', 'New Zealand'] }
};

const continents = [
  { name: 'Western Europe', minLat: 42, maxLat: 60, minLng: -5, maxLng: 15, weight: 2 },
  { name: 'Eastern Europe', minLat: 44, maxLat: 60, minLng: 15, maxLng: 40, weight: 2 },
  { name: 'Southern Europe', minLat: 36, maxLat: 46, minLng: -9, maxLng: 28, weight: 2 },
  { name: 'Scandinavia', minLat: 55, maxLat: 71, minLng: 5, maxLng: 31, weight: 1 },
  { name: 'UK & Ireland', minLat: 50, maxLat: 60, minLng: -10, maxLng: 2, weight: 1 },
  { name: 'China Mainland', minLat: 18, maxLat: 53, minLng: 73, maxLng: 135, weight: 3 },
  { name: 'Japan', minLat: 30, maxLat: 46, minLng: 129, maxLng: 146, weight: 1 },
  { name: 'Korea', minLat: 33, maxLat: 43, minLng: 124, maxLng: 131, weight: 1 },
  { name: 'Mainland Southeast Asia', minLat: 5, maxLat: 28, minLng: 92, maxLng: 109, weight: 2 },
  { name: 'Indonesia West', minLat: -11, maxLat: 6, minLng: 95, maxLng: 120, weight: 1 },
  { name: 'Philippines', minLat: 5, maxLat: 19, minLng: 117, maxLng: 127, weight: 1 },
  { name: 'India', minLat: 8, maxLat: 35, minLng: 68, maxLng: 97, weight: 2 },
  { name: 'Pakistan & Afghanistan', minLat: 24, maxLat: 38, minLng: 60, maxLng: 75, weight: 1 },
  { name: 'Levant & Turkey', minLat: 31, maxLat: 42, minLng: 26, maxLng: 45, weight: 1 },
  { name: 'Arabian Peninsula', minLat: 12, maxLat: 32, minLng: 34, maxLng: 60, weight: 1 },
  { name: 'Iran', minLat: 25, maxLat: 40, minLng: 44, maxLng: 63, weight: 1 },
  { name: 'Eastern USA', minLat: 25, maxLat: 50, minLng: -98, maxLng: -67, weight: 2 },
  { name: 'Western USA', minLat: 31, maxLat: 49, minLng: -125, maxLng: -102, weight: 2 },
  { name: 'Eastern Canada', minLat: 43, maxLat: 62, minLng: -95, maxLng: -52, weight: 1 },
  { name: 'Western Canada', minLat: 49, maxLat: 62, minLng: -140, maxLng: -95, weight: 1 },
  { name: 'Mexico', minLat: 14, maxLat: 32, minLng: -118, maxLng: -86, weight: 1 },
  { name: 'Central America', minLat: 7, maxLat: 18, minLng: -93, maxLng: -77, weight: 1 },
  { name: 'Brazil North', minLat: -10, maxLat: 5, minLng: -74, maxLng: -35, weight: 2 },
  { name: 'Brazil South', minLat: -34, maxLat: -10, minLng: -58, maxLng: -35, weight: 1 },
  { name: 'Andean Countries', minLat: -18, maxLat: 12, minLng: -81, maxLng: -66, weight: 1 },
  { name: 'Chile & Argentina', minLat: -55, maxLat: -22, minLng: -75, maxLng: -53, weight: 1 },
  { name: 'North Africa', minLat: 15, maxLat: 37, minLng: -17, maxLng: 52, weight: 2 },
  { name: 'West Africa', minLat: 4, maxLat: 20, minLng: -17, maxLng: 16, weight: 1 },
  { name: 'East Africa', minLat: -12, maxLat: 16, minLng: 22, maxLng: 51, weight: 1 },
  { name: 'Southern Africa', minLat: -35, maxLat: -15, minLng: 11, maxLng: 42, weight: 1 },
  { name: 'Australia', minLat: -44, maxLat: -10, minLng: 113, maxLng: 154, weight: 2 },
  { name: 'New Zealand', minLat: -47, maxLat: -34, minLng: 166, maxLng: 179, weight: 1 }
];

module.exports = {
  countryBoundsData,
  cityBoundsData,
  cityKeywords,
  regionMap,
  continents
};

