/**
 * OpenAI Image Generation Service
 * 
 * Handles image generation and editing using OpenAI API.
 * Extracted from openaiService.js (Phase 5.3)
 */

import OpenAI from 'openai';
import { sanitizeText, cleanMarkdown } from '../../utils/textSanitizer';
import { getStaticFileUrl } from '../../utils/urlUtils';
import fs from 'fs';
import { v4 as uuidv4 } from 'uuid';
import { createTempFilePath } from '../../utils/tempFileUtils';
import { Request } from 'express';
import logger from '../../utils/logger';

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
});

/**
 * Image generation result (buffer)
 */
interface ImageGenerationResult {
    text?: string;
    imageBuffer?: Buffer;
    error?: string;
}

/**
 * WhatsApp image result
 */
interface WhatsAppImageResult {
    success: boolean;
    imageUrl?: string;
    description?: string;
    fileName?: string;
    textOnly?: boolean;
    error?: string;
}

/**
 * Generate image with text (returns buffer)
 */
/**
 * Internal helper to execute OpenAI image generation
 */
async function baseGenerate(prompt: string): Promise<{ buffer: Buffer; revisedPrompt: string }> {
    const cleanPrompt = sanitizeText(prompt);
    const response = await openai.images.generate({
        model: "gpt-image-1",
        prompt: cleanPrompt,
        n: 1,
        quality: "high",
        output_format: "png"
    });

    if (!response.data || response.data.length === 0 || !response.data[0]) {
        throw new Error('No image generated by OpenAI');
    }

    const imageData = response.data[0];
    if (!imageData.b64_json) {
        throw new Error('No base64 image data found in OpenAI response');
    }

    return {
        buffer: Buffer.from(imageData.b64_json, 'base64'),
        revisedPrompt: imageData.revised_prompt || prompt
    };
}

/**
 * Internal helper to execute OpenAI image editing
 */
async function baseEdit(prompt: string, imageBuffer: Buffer): Promise<{ buffer: Buffer; revisedPrompt: string }> {
    const cleanPrompt = sanitizeText(prompt);
    const imageFile = new File([imageBuffer], 'image.jpg', { type: 'image/jpeg' });

    const response = await openai.images.edit({
        model: "gpt-image-1",
        image: imageFile,
        prompt: cleanPrompt,
        input_fidelity: "high",
        quality: "high",
        output_format: "png"
    });

    if (!response.data || response.data.length === 0 || !response.data[0]) {
        throw new Error('No image generated by OpenAI edit');
    }

    const imageData = response.data[0];
    if (!imageData.b64_json) {
        throw new Error('No base64 image data found in OpenAI edit response');
    }

    return {
        buffer: Buffer.from(imageData.b64_json, 'base64'),
        revisedPrompt: imageData.revised_prompt || prompt
    };
}

/**
 * Common processing for WhatsApp image results (save to disk and return URL)
 */
function processWhatsAppImage(
    buffer: Buffer,
    revisedPrompt: string,
    req: Request | null,
    prefix: string = 'openai'
): WhatsAppImageResult {
    const fileName = `${prefix}_${uuidv4()}.png`;
    const filePath = createTempFilePath(fileName);

    fs.writeFileSync(filePath, buffer);
    const imageUrl = getStaticFileUrl(fileName, req);

    return {
        success: true,
        imageUrl,
        description: cleanMarkdown(revisedPrompt),
        fileName
    };
}

/**
 * Generate image with text (returns buffer)
 */
export async function generateImageWithText(prompt: string): Promise<ImageGenerationResult> {
    try {
        logger.info('🎨 Starting OpenAI image generation');
        const { buffer, revisedPrompt } = await baseGenerate(prompt);
        logger.info('✅ OpenAI image generated successfully');
        return { text: revisedPrompt, imageBuffer: buffer };
    } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        logger.error('❌ OpenAI image generation error:', { error: errorMessage });
        throw err;
    }
}

/**
 * Edit image with text (returns buffer)
 */
export async function editImageWithText(prompt: string, imageBuffer: Buffer): Promise<ImageGenerationResult> {
    try {
        logger.info('🖼️ Starting OpenAI image editing');
        const { buffer, revisedPrompt } = await baseEdit(prompt, imageBuffer);
        logger.info('✅ OpenAI image edited successfully');
        return { text: revisedPrompt, imageBuffer: buffer };
    } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : String(err);
        logger.error('❌ OpenAI image edit error:', { error: errorMessage });
        throw err;
    }
}

/**
 * Generate image for WhatsApp (returns URL)
 */
export async function generateImageForWhatsApp(prompt: string, req: Request | null): Promise<WhatsAppImageResult> {
    try {
        logger.info('🎨 Starting OpenAI image generation for WhatsApp');
        const { buffer, revisedPrompt } = await baseGenerate(prompt);
        return processWhatsAppImage(buffer, revisedPrompt, req, 'openai');
    } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : 'Unknown error during image generation';
        logger.error('❌ OpenAI image generation error:', { error: errorMessage });
        return { success: false, error: errorMessage };
    }
}

/**
 * Edit image for WhatsApp (returns URL)
 */
export async function editImageForWhatsApp(prompt: string, base64Image: string, req: Request | null): Promise<WhatsAppImageResult> {
    try {
        logger.info('🖼️ Starting OpenAI image editing for WhatsApp');
        const imageBuffer = Buffer.from(base64Image, 'base64');
        const { buffer, revisedPrompt } = await baseEdit(prompt, imageBuffer);
        return processWhatsAppImage(buffer, revisedPrompt, req, 'openai_edit');
    } catch (err: unknown) {
        const errorMessage = err instanceof Error ? err.message : 'Unknown error during image editing';
        logger.error('❌ OpenAI image edit error:', { error: errorMessage });
        return { success: false, error: errorMessage };
    }
}

